apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: vcluster
  labels:
    crossplane.io/xrd: jfrogvirtualenv.crossplane.jfrog.io
spec:
  compositeTypeRef:
    apiVersion: jfrogvirtualenv.crossplane.jfrog.io/v1alpha1
    kind: JfrogCrossplanePlatform
  resources:
  - name: vcluster
    base:
      apiVersion: helm.crossplane.io/v1beta1
      kind: Release
      name: vcluster
      spec:
        forProvider:
          chart:
            name: vcluster
            repository: https://charts.loft.sh
            version: 0.14.0
          namespace: vcluster-namespace
          values:
            syncer:
              extraArgs:
              - --out-kube-config-secret=vcluster-kubeconfig
              - --out-kube-config-server=https://vcluster-test.vcluster-test.svc.cluster.local
              - --tls-san=vcluster-test.vcluster-test.svc.cluster.local
            sync:
              ingresses:
                enabled: true
              poddisruptionbudgets:
                enabled: true
        providerConfigRef:
          name: crossplane-helm-providerconfig
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.namespace
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.name
      toFieldPath: metadata.name
      transforms:
      - type: string
        string:
          fmt: "%s-vcluster"
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: metadata.name
        - fromFieldPath: metadata.name
        strategy: string
        string:
          fmt: "--out-kube-config-server=https://%s-vcluster.%s.svc.cluster.local"
      toFieldPath: spec.forProvider.values.syncer.extraArgs[1]
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: metadata.name
        - fromFieldPath: metadata.name
        strategy: string
        string:
          fmt: "--tls-san=%s-vcluster.%s.svc.cluster.local"
      toFieldPath: spec.forProvider.values.syncer.extraArgs[2]
      

  - name: observe-delete-namespace
    base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      metadata:
        name: foo
      spec:
        managementPolicy: ObserveDelete
        forProvider:
          manifest:
            apiVersion: v1
            kind: Namespace
        providerConfigRef:
          name: kubernetes-provider
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.name
      toFieldPath: metadata.name


  - name: s3Bucket
    base:
      apiVersion: s3.aws.upbound.io/v1beta1
      kind: Bucket
      metadata:
        name: crossplane-quickstart-bucket
      spec:
        forProvider:
          name: default
          region: "us-east-2"
    patches:
      - type: FromCompositeFieldPath
        fromFieldPath: metadata.name
        toFieldPath: spec.forProvider.name
      - type: FromCompositeFieldPath
        fromFieldPath: metadata.name
        toFieldPath: metadata.name
        transforms:
        - type: string
          string:
            fmt: "%s-s3bucket"
      - fromFieldPath: spec.region
        toFieldPath: spec.forProvider.region
        transforms:
          - type: map
            map: 
              EU: "eu-north-1"
              US: "us-east-2"