apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xs3bucket.crossplane.jfrog.io
spec:
  group: crossplane.jfrog.io
  names:
    kind: XS3Bucket
    plural: xs3buckets
  claimNames:
    kind: S3Bucket
    plural: s3buckets
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              s3bucket:
                type: object
                properties:
                  region:
                    type: string
                    oneOf:
                      - pattern: '^EU$'
                      - pattern: '^US$'
                required:
                  - region