apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  labels:
    crossplane.io/xrd: xrdss.crossplane.jfrog.io
    provider: aws
  name: rds
spec:
  compositeTypeRef:
    apiVersion: crossplane.jfrog.io/v1alpha1
    kind: XRds
  resources:
  - name: rdsDBInstance
    base:
      apiVersion: rds.aws.upbound.io/v1beta1
      kind: Instance
      metadata:
        annotations: 
          crossplane.io/external-name: "crossplane-rds-instance"
      spec:
        forProvider:
          instanceClass: db.t3.medium
          allocatedStorage: 20
          dbSubnetGroupName: k8s-dev-ap-south-1
          # securityGroupNames:
          #   - k8s-dev-ap-south-1-postgresql
          vpcSecurityGroupIds:
            - sg-02fe99b0cf5bf1417
          autoGeneratePassword: true
          passwordSecretRef:
            key: password
            name: rdspassword
            namespace: crossplane-system
          deletetionProtection: false
          maintenanceWindow: Sun:02:00-Sun:03:00
          backupWindow: 01:00-02:00
          skipFinalSnapshot: true
          backupRetentionPeriod: 7
          storageEncrypted: true
          tags:
            application: rds-example
        writeConnectionSecretToRef:
          namespace: crossplane-system
          name: newrds
        providerConfigRef:
          name: crossplane-aws-providerconfig
    patches:
      - fromFieldPath: metadata.labels['crossplane.io/claim-name']
        toFieldPath: metadata.annotations[crossplane.io/external-name]
      - fromFieldPath: spec.parameters.region
        toFieldPath: spec.forProvider.region
      - fromFieldPath: spec.parameters.instanceClass
        toFieldPath: spec.forProvider.instanceClass
      - fromFieldPath: spec.parameters.dbName
        toFieldPath: spec.forProvider.dbName
      - fromFieldPath: spec.parameters.engine
        toFieldPath: spec.forProvider.engine
      - fromFieldPath: spec.parameters.engineVersion
        toFieldPath: spec.forProvider.engineVersion
      - fromFieldPath: spec.parameters.username
        toFieldPath: spec.forProvider.username
      - fromFieldPath: spec.parameters.dbSubnetGroupName
        toFieldPath: spec.forProvider.dbSubnetGroupName
      - fromFieldPath: spec.parameters.vpcSecurityGroupIds
        toFieldPath: spec.forProvider.vpcSecurityGroupIds
      - fromFieldPath: spec.parameters.availabilityZone
        toFieldPath: spec.forProvider.availabilityZone
      - fromFieldPath: spec.parameters.deletetionProtection
        toFieldPath: spec.forProvider.deletetionProtection
      - fromFieldPath: spec.parameters.maintenanceWindow
        toFieldPath: spec.forProvider.maintenanceWindow
      - fromFieldPath: spec.parameters.backupWindow
        toFieldPath: spec.forProvider.backupWindow
      - fromFieldPath: spec.parameters.skipFinalSnapshot
        toFieldPath: spec.forProvider.skipFinalSnapshot
      - fromFieldPath: spec.parameters.backupRetentionPeriod
        toFieldPath: spec.forProvider.backupRetentionPeriod
      - fromFieldPath: spec.parameters.tags
        toFieldPath: spec.forProvider.tags
      # set the secret name to the claim name
      - fromFieldPath: "metadata.labels[crossplane.io/claim-name]"
        toFieldPath: "spec.writeConnectionSecretToRef.name"
        transforms:
          - type: string
            string:
              fmt: "%s-pginstance"
      # change secret namespace to the one of the claim
      - fromFieldPath: "metadata.labels[crossplane.io/claim-namespace]"
        toFieldPath: "spec.writeConnectionSecretToRef.namespace"
      # set label app = name of the original claim
      - fromFieldPath: "metadata.labels[crossplane.io/claim-name]"
        toFieldPath: "metadata.labels[crossplane.io/app]"
      # set the name of the external resource to be the name of the claim
      - fromFieldPath: "metadata.labels[crossplane.io/claim-name]"
        toFieldPath: "metadata.annotations[crossplane.io/external-name]"
  # - base:
  #     apiVersion: secretsmanager.aws.crossplane.io/v1beta1
  #     kind: Secret
  #     spec:
  #       forProvider:
  #         region: ap-south-1
  #         description: "Rds master password"
  #         forceDeleteWithoutRecovery: false
  #         recoveryWindowInDays: 7
  #         stringSecretRef:
  #           key: password
  #       providerConfigRef:
  #         name: crossplane-aws-providerconfig
  #   name: rdsMasterPassword
  #   patches:
  #     - fromFieldPath: spec.parameters.tags
  #       toFieldPath: spec.forProvider.tags
  #     - fromFieldPath: metadata.labels['crossplane.io/claim-name']
  #       toFieldPath: spec.forProvider.stringSecretRef.namespace
  #     - fromFieldPath: metadata.labels['crossplane.io/claim-name']
  #       toFieldPath: spec.forProvider.stringSecretRef.name