apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xrdss.crossplane.jfrog.io
spec:
  claimNames:
    kind: RDS
    plural: rdss
  group: crossplane.jfrog.io
  names:
    kind: XRds
    plural: xrdss
  versions:
  - name: v1alpha1
    referenceable: true
    served: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  tags:
                    type: array
                    items:
                      type: object
                      properties:
                        key:
                          type: string
                        value:
                          type: string
                  region:
                    type: string
                  instanceClass:
                    type: string
                  engine:
                    type: string
                  engineVersion:
                    type: string
                  dbName:
                    type: string
                  username:
                    type: string
                  dbSubnetGroupName:
                    type: string
                  # securityGroupNames:
                  #   type: array
                  availabilityZone:
                    type: string
                  backupRetentionPeriod:
                    type: integer
                  deletetionProtection:
                    type: boolean
                  skipFinalSnapshot:
                    type: boolean
                  backupWindow:
                    type: string
                  maintenanceWindow:
                    type: string
                required:
                  - tags
                  - engineVersion
                  - instanceClass
                  - dbName